### ISSUE TITLE
login page

### ISSUE THREAD

**Issue by kaiyukang** [Gmyth/Uplan#10]
build the login page and its front-end api, cause our current login page is just for test, doesn't have any ui.

**Comment by Gmyth** [comment]
Since the API test is done on last Sprint, we will finish the login page as soon as possible. Login page is expecting finishing on the end of this week. The basic function of login page need to achieve is check user key, sign up page. Otherwise,

**Comment by kaiyukang** [comment]
the login webpage done, working on store function and check user key stuff and connection between our database

**Comment by kaiyukang** [comment]
issue done
